<div class="uap-wrapper">
		<div class="uap-stuffbox">
			<form action="<?php echo $data['url-manage'];?>" method="post">

				<input type="hidden" name="uap_admin_forms_nonce" value="<?php echo wp_create_nonce( 'uap_admin_forms_nonce' );?>" />

				<h3 class="uap-h3"><?php esc_html_e('Add/Edit Referral', 'uap');?></h3>

				<div class="inside">
					<div class="uap-form-line">
						<label class="uap-label"><?php esc_html_e('Click ID', 'uap');?></label>
						<input type="text" value="<?php echo $data['metas']['visit_id'];?>" name="visit_id" />
						<span class="uap-sublabel"><?php esc_html_e('Optional. Represents  Click entry available on ', 'uap');?><a href="<?php echo admin_url('admin.php?page=ultimate_affiliates_pro').'&tab=visits';?>" target="_blank"><?php esc_html_e('Clicks', 'uap');?></a><?php esc_html_e(' section', 'uap');?></span>
					</div>
					<div class="uap-form-line">
						<label class="uap-label"><?php esc_html_e('Referrer Customer WP ID', 'uap');?></label>
						<input type="text" value="<?php echo $data['metas']['refferal_wp_uid'];?>" name="refferal_wp_uid" />
						<span class="uap-sublabel"><?php esc_html_e('Optional. Represents  WordPress User ID associated with customer referred by an Affiliate', 'uap');?></span>
					</div>
					<div class="uap-form-line">
						<label class="uap-label"><?php esc_html_e('Affiliate Campaign', 'uap');?></label>
						<input type="text" value="<?php echo $data['metas']['campaign'];?>" name="campaign" />
						<span class="uap-sublabel"><?php esc_html_e('Optional. The Campaign slug generated by Affiliate user via My Account page.', 'uap');?></span>
					</div>
					<div class="uap-form-line">
						<label class="uap-label "><?php esc_html_e('Affiliate User', 'uap');?><span class="uap-color-red">*</span></label>
						<select name="affiliate_id"><?php
							foreach ($data['affiliates'] as $k=>$v):
								$selected = ($data['metas']['affiliate_id']==$k) ? 'selected' : '';
								?>
								<option value="<?php echo $k;?>" <?php echo $selected;?>><?php echo $v['username'];?></option>
								<?php
							endforeach;
						?></select>
					</div>
					<div class="uap-form-line">
						<label class="uap-label"><?php esc_html_e('Description', 'uap');?></label>
						<textarea name="description"><?php echo $data['metas']['description'];?></textarea>
						<span class="uap-sublabel"><?php esc_html_e('Optional. Additional description for current Referral', 'uap');?></span>
					</div>
					<div class="uap-form-line">
						<label class="uap-label"><?php esc_html_e('Source', 'uap');?></label>
						<input type="text" value="<?php echo $data['metas']['source'];?>" name="source" />
						<span class="uap-sublabel"><?php esc_html_e('Optional. Source slug, predefined (ex: woo, ump, edd, ulp, bonus, User SignUp, from landing commissions)  or custom one ', 'uap');?></span>
					</div>
					<div class="uap-form-line">
						<label class="uap-label"><?php esc_html_e('Reference', 'uap');?></label>
						<input type="text" value="<?php echo $data['metas']['reference'];?>" name="reference" />
						<span class="uap-sublabel"><?php esc_html_e('Optional. Such Order ID for Woo,UMP or User ID for User SignUp', 'uap');?></span>
					</div>
					<div class="uap-form-line">
						<label class="uap-label"><?php esc_html_e('Reference Details', 'uap');?></label>
						<textarea name="reference_details"><?php echo $data['metas']['reference_details'];?></textarea>
						<span class="uap-sublabel"><?php esc_html_e('Optional. Additional details for current Reference', 'uap');?></span>
					</div>
					<div class="uap-display-none <?php echo (!empty($data['metas']['parent_referral_id']) || !empty($data['metas']['child_referral_id']) || $indeed_db->is_magic_feat_enable('mlm')) ? 'uap-display-block' : ''; ?> " >
					<div class="uap-form-line">
						<label class="uap-label"><?php esc_html_e('Referral Parent ID', 'uap');?></label>
						<input type="text" value="<?php echo $data['metas']['parent_referral_id'];?>" name="parent_referral_id" />
						<span class="uap-sublabel"><?php esc_html_e('Optional and for MLM workflow only. Represents the Referral ID received by UpLine Affiliate user', 'uap');?></span>
					</div>
					<div class="uap-form-line">
						<label class="uap-label"><?php esc_html_e('Referral Child ID', 'uap');?></label>
						<input type="text" value="<?php echo $data['metas']['child_referral_id'];?>" name="child_referral_id" />
						<span class="uap-sublabel"><?php esc_html_e('Optional and for MLM workflow only. Represents the Referral ID received by DownLine Affiliate user', 'uap');?></span>
					</div>
				</div>

					<div class="uap-form-line">
						<label class="uap-label"><?php esc_html_e('Amount', 'uap');?><span class="uap-color-red">*</span></label>
						<input type="number" min="0" step='<?php echo uapInputNumerStep();?>' value="<?php echo $data['metas']['amount'];?>" name="amount" />
						<span class="uap-sublabel"><?php esc_html_e('Required. Positive value.', 'uap');?></span>
					</div>
					<div class="uap-form-line">
						<label class="uap-label"><?php esc_html_e('Currency', 'uap');?><span class="uap-color-red">*</span></label>
						<select name="currency"><?php
							$currency = uap_get_currencies_list();
							foreach ($currency as $k=>$v){
								$selected = ($k==$data['metas']['currency']) ? 'selected' : '';
								?>
								<option value="<?php echo $k;?>" <?php echo $selected;?> ><?php echo $v;?></option>
								<?php
							}
						?></select>
					</div>
					<div class="uap-form-line">
						<label class="uap-label"><?php esc_html_e('Date', 'uap');?><span class="uap-color-red">*</span></label>
						<input type="text" value="<?php echo $data['metas']['date'];?>" name="date" id="referrals_date"/>
						<span class="uap-sublabel"><?php esc_html_e('Required. Date and Time when current Referral have been created', 'uap');?></span>
					</div>
					<div class="uap-form-line">
						<label class="uap-label"><?php esc_html_e('Status', 'uap');?></label>
						<select name="status"><?php
							foreach ($data['status_posible'] as $k=>$v):
								$selected = ($data['metas']['status']==$k) ? 'selected' : '';
								?>
								<option value="<?php echo $k;?>" <?php echo $selected;?>><?php echo $v;?></option>
								<?php
							endforeach;
						?></select>
					</div>
					<div class="uap-form-line">
						<label class="uap-label"><?php esc_html_e('Payment', 'uap');?></label>
						<select name="payment"><?php
							foreach ($data['payment_posible'] as $k=>$v):
								$selected = ($data['metas']['payment']==$k) ? 'selected' : '';
								?>
								<option value="<?php echo $k;?>" <?php echo $selected;?>><?php echo $v;?></option>
								<?php
							endforeach;
						?></select>
						<span class="uap-sublabel"><?php esc_html_e('Optional. Choose Paid if current Referral have been withdrawn by Affiliate user', 'uap');?></span>
					</div>

					<div id="uap_save_changes" class="uap-submit-form">
						<input type="submit" value="<?php esc_html_e('Save Changes', 'uap');?>" name="save" class="button button-primary button-large">
					</div>
				</div>

				<input type="hidden" name="id" value="<?php echo $data['metas']['id'];?>" />

			</form>
		</div>

</div>
